README.md
lib/proxy.js

feature: onCertificateRequired and onCertificateMissing added to the module pattern

onCertificateRequired and onCertificateMissing module pattern

---

lib/proxy.js

#13
Wasn't quite sure what to do in terms of unit testing but i've tested it locally with a bunch of requests.

feat: proxy/ctx.onResponseEnd

---

README.md
lib/ca.js
lib/proxy.js
package.json

Adding a small CA in pure Javascript to allow automatic SSL certificate generation.

Add node-forge to allow automatic SSL certificate generation.

---

README.md
lib/proxy.js
test/preventRequest.js
test/processFullResponseBody.js

I also added more test use cases and added some documentation

Don't write chunk to response when it is null

---

README.md

fix bad link syntax

---

README.md
lib/proxy.js
test/modifyGoogle.js
test/onCertificateMissing.js
test/onCertificateRequired.js
test/preventRequest.js
test/processFullResponseBody.js
test/websocket.js

- Catch more errors
- Added `errorKind` arguments to onError handler
- Added `silent` option to listen

Improved error catching and reporting

---

bin/mitm-proxy.js
lib/proxy.js
package.json

- Upgrade dependencies
- Fill `repository` field to prevent npm warning
- Added `bin` field
- Added more descriptive fields
- Added myself in contributors field
- Bumped version to 0.2.0

Package.json

---

README.md
examples/modifyGoogle.js
examples/onCertificateMissing.js
examples/onCertificateRequired.js
examples/preventRequest.js
examples/processFullResponseBody.js
examples/websocket.js
lib/ca.js
lib/proxy.js
package.json
test/01_proxy.js

Normalize and Bump version

---

README.md
bin/mitm-proxy.js
examples/wildcard.js
lib/ca.js
lib/middleware/wildcard.js
lib/proxy.js
package.json

- Modifiy proxy code so it can handles Wildcard and multiple domains certificates
- Add `Proxy.wilcard` middleware to generate wildcard certificates by default (so it generate less certificates)
- Code cleanup

Wilcard certificates

---

examples/forwardHttps.js
lib/proxy.js

Custom HTTPS proxy tunnel handler supporting #50

Add onConnect callback for handling CONNECT method

---

examples/forwardHttps.js
lib/proxy.js

Sorry, I had missed onConnect for middleware in last PR, add it now.

Missing onConnect for middleware

---

lib/proxy.js

added options forceChunkedRequest to deal with: https://github.com/joeferner/node-http-mitm-proxy/issues/129 and https://github.com/joeferner/node-http-mitm-proxy/pull/94

Deleted Content-Length should be optional

---

README.md

it seems one more line breaking is required.

fix readme titles are not showing correctly on github

---

lib/proxy.js

This address bug https://github.com/joeferner/node-http-mitm-proxy/issues/149 (maybe it even fixes it - a review would be nice here "works on my machine" ;)

fix upgradeReq is undefined

---

lib/proxy.js

resolves #139 by using the same code node uses to determine if headers are valid or not.

filter invalid response headers

---

README.md
bin/mitm-proxy.js
test/01_proxy.js

follow-up to https://github.com/joeferner/node-http-mitm-proxy/pull/178

cleanup silent option

---

lib/proxy.js

Fixed #205 (97:Callback is not a function)

---

bin/mitm-proxy.js
package-lock.json
package.json

Migrate to yargs
Update mocha
Update node-forge

Update various packages to fix npm audit failures.

---

lib/proxy.js

Prevent crash on server start

---

lib/proxy.js

Prevent uncatchable errors like https://github.com/Apollon77/daikin-controller-cloud/issues/15#issuecomment-878462215

Prevent uncatchable exceptions on close

---

.github/workflows/tests.yml

Update node versions to latest LTS versions

update node versions for testing
