lib/proxy.js
Thanks for your amazing work on this. I'm using it for a research project. I found a little bug where it was failing to proxy the requests of the form `http://user:pass@my_host:port/path` considering `user` as the hostname instead of `my_host`
This should fix it. I've tried it and it seems to work as expected.
=> uses the standard library to parse host and port

lib/proxy.js
The previous PR caused an unwnated issue, resolved here. The URL parsing is only done when the url is indeed a URL of the form `http*` and skipped when its only of the format `host[:port]`
=> Host port fix

lib/proxy.js
The result of a call to pipe() is another stream.Readable, but filter is a stream.Writable.
The returned value 'true' is never used.
http.IncomingMessage is not a stream.Writable.
=> Fixes for issues found by Closure Compiler.

lib/proxy.js
For now, proxy to server request errors are not catched and so crash the proxy at the first error, including domain not found errors when the requested host does not exists or is down.
https://github.com/joeferner/node-http-mitm-proxy/issues/18
This pull request:
- catch thoose error in the onError handler
- send a default error response to the client after onError if the response have not been sent yet.
- Fix a typo
=> Handle request error (ex: Domain not found errors)

lib/proxy.js
Prevent the proxy server from crashing from any kind of request/response error (like ECONNRESET or whatever that may happen).
Instead it forward the error to onError handlers
=> Handle error event on all requests and responses

lib/ca.js
Firefox reject server certificate that don't have a unique serial number.
See @VictorBjelkholm comment: https://github.com/joeferner/node-http-mitm-proxy/issues/16#issuecomment-159748949
This pull request fixes this issue by using randomly generated serial number.
=> Use randomly generated CA serial numbers

lib/ca.js
Before the certs and keys subfolders where not created when the baseFolder already exists.
This PR fixes this issue
=> Fix CA folders creation

lib/proxy.js
Before SSL encryption was guessed with the port of the request which is
not accurate and it caused issues (See #34).
The new resolving process uses the first byte of data to detect SSL,
using an euristic inspired from https://gist.github.com/tg-x/835636
Fixes #34
=> Rewrited SSL encryption Resolving

lib/proxy.js
Some of the response headers may contain white spaces at the beginning or end,
this throws an exception from node native API
=> Bug fix in sending back response headres containing white spaces

lib/proxy.js
`onRequestEnd` is required to capture the whole request body like so:
let chunks = [];
ctx.onRequestData(function(ctx, chunk, callback) {
chunks.push(chunk);
return callback(null, chunk);
});
ctx.onRequestEnd(function(ctx, chunk, callback) {
let body = Buffer.concat(chunks)).toString();
// do something with request body
return callback(null, chunk);
});
Fixes #44
=> Add requestEnd event

README.md, lib/proxy.js
Small changes to my yesterday's PR:
- I changed `onRequestEnd` signature (`ctx, chunk, callback` :arrow_right: `ctx, callback`) to match `onResponseEnd` because:
- it makes API more consistent and
- unlike previous version (where last chunk went to `onRequestEnd`) this is a non-breaking change (all chunks go to `onRequestData` as before)
- I've also updated the docs:
- `onRequestEnd` was added and
- `onResponseEnd` was updated (docs suggested that it's available only on `ctx` while it was also available on `proxy` + there was a minor typo ("as" :arrow_right: "has")).
=> modify onRequestEnd to match onResponseEnd

lib/proxy.js
Added onRequestHeaders and onResponseHeaders, to ease interception and modification of headers before relayed on.
added exports.Proxy = Proxy so that one can use the object as a base for other objects.
=> Add methods / Expose Proxy to allow inherintance

lib/proxy.js
Allows to write
```
proxy.onRequest(handleIncomingRequest.bind(this))
.onResponse(handleIncomingResponse.bind(this))
.onError(handleProxyError.bind(this))
.listen({port: port});
```
instead of:
```
proxy.onRequest(handleIncomingRequest.bind(this));
proxy.onResponse(handleIncomingResponse.bind(this));
proxy.onError(handleProxyError.bind(this));
proxy.listen({port: port});
```
same for context
Fix #43
=> Allow method chaining

README.md, examples/websocket.js, lib/proxy.js
- Add a `WebSocketFrame` event handler with `type` and `fromServer` discriminator parameters which also handles `message` frames
- internally bind `WebSocketMessage` and `WebSocketSend` handlers on the `WebSocketFrame` handler
=> Websocket ping pong

README.md, lib/proxy.js
- add timeout option to listen method
- use it to set internal [http & https servers
timeout](https://nodejs.org/api/http.html#http_server_timeout)
- set default to 0 (i.e. no timeout)
Fix #56
=> Add timeout option

README.md, lib/proxy.js
`agent: false` option had been set in order not to use the globalAgent which may be set to a proxy agent pointing to the currently running proxy.
But it also disable request pooling:
https://nodejs.org/api/http.html#http_http_request_options_callback
This PR fix this by setting agent to an internal agent (tweakable through options httpAgent and httpsAgent)
This allows a small boost of performance
=> replace agent: false by internal agent 

README.md, lib/proxy.js
When enabled, it allows to handle all HTTPS requests with a single
internal server which free ports and give a small performance boost.
The downside is that the proxy would probably not work with clients that
don't supports SNI (obsolete clients https://en.wikipedia.org/wiki/Server_Name_Indication)
=> add `forceSNI` option to listen method

lib/proxy.js
[HPKP](https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning) is an Http Extension used to prevent usage of MITM Proxy.
The server add headers to http response with a hash to compare used certificates among.
As a result, clients supporting HPKP may fail and/or report errors with MITM proxy, even when the fake CA is installed locally.
The PR filter thoose headers.
It allow to prevent errors and report when the mitm proxy is installed permanently.
Due to HPKP cache, there may still be errors when the client have browsed without the proxy enabled before (or using previous versions of the proxy)
=> Filter HPKP Headers

README.md, lib/proxy.js
add httpsPort and useNamedSocket options:
- httpsPort: tweak internally used port in case of single https server (forceSNI must be enabled).
- useNamedSocket: use named socket (i.e. unix socket or named pipe) instead of TCP ports for internal server(s). It should makes it faster. Works well on unix. I got strange troubles on windows. That why I disabled it by default
=> Unix socket

README.md, lib/proxy.js
Support of keepAlive.
Sockets between client and proxy and between proxy and server are kept alive for a while and reused for successives requests (when supported by server and client).
Timeout an max open socket limits are default ones. 
I made a few tests without any issue. It seems to really boost the perfs.
=> Keep alive

README.md, lib/proxy.js
useNamedSocket option is not working properly.
- On windows + nodejs 5.6 it crash nodejs
- On unix it works on most requests but fail on others (ex: all images
on twitter), when creating the internal socket connection.
Both may be due to concurrent connection over the same named pipe but I
don't have enough information to be sure.
This experiment is not yet working and should be removed from master
=> Remove useNamedSocket option

lib/proxy.js
- Don't forward proxy-* headers to server (most clients add headers for the proxy that should not be transfered to the server)
- In keepAlive mode, handles `proxy-connection: keep-alive` header
- In keepAlive connection, don't force connection header (leave it untouched even when it does not exists)
=> Various keepAlive fixes & improvements

lib/ca.js
Hello! I ran into some issues trying to use node-http-mitm-proxy with IP addresses. It works great except that the generated cert has an invalid subject alternative name.
This [node-forge example](https://github.com/digitalbazaar/forge/blob/master/README.md#x509) shows how the subject alt name should be specified for an IP address. I've followed that example.
Please let me know if there is anything that I can do to improve this PR or my commit and I'd be happy to do so. Thanks! :)
=> support automatic cert creation for IP addresses

lib/proxy.js
This forward the request and response filters errors to onError handler.
It allows to catch gunzip module errors for example.
=> handle response and request filters errors

lib/middleware/gunzip.js
Otherwise the server may use another content-encoding algorythm (like SDCH for example)
Fix #80
=> set accept-encoding header to gzip when using gunzip middleware

lib/proxy.js
Hey and thanks for this great project, which supports the core of my [pokemon-go-mitm-node](https://github.com/rastapasta/pokemon-go-mitm-node) project.
Just ran into one issue:
When tampering request bodys of requests sent from the client to the proxy, the content-length was kept in the headers - in the response handling they got taken out already.
By removing it from the client request, the encoding will be set automatically to chunked -> no content-length needed -> #win and injectability :) 
Cheers!
=> Removing Content-Length from clientToProxyRequest

lib/proxy.js
Surfing e.g. on github I get this error a lot:
```
/home/vagrant/projects/grape/grape-web-client/node_modules/ws/lib/WebSocket.js:197
if (this.readyState !== WebSocket.OPEN) throw new Error('not opened');
^
Error: not opened
at WebSocket.resume (/home/vagrant/projects/grape/grape-web-client/node_modules/ws/lib/WebSocket.js:197:49)
at WebSocket.<anonymous> (/home/vagrant/projects/grape/grape-web-client/node_modules/http-mitm-proxy/lib/proxy.js:613:36)
at emitNone (events.js:86:13)
at WebSocket.emit (events.js:185:7)
at WebSocket.establishConnection (/home/vagrant/projects/grape/grape-web-client/node_modules/ws/lib/WebSocket.js:887:8)
at ClientRequest.upgrade (/home/vagrant/projects/grape/grape-web-client/node_modules/ws/lib/WebSocket.js:778:25)
at ClientRequest.g (events.js:286:16)
at …
```
=> Fix websocket error: not opened

README.md, index.d.ts, package.json
added typescript definitions for use with people using Typsecript.
also FYI (but not related to this pull request) I rewrote the entire ```node-http-mitm-proxy``` project in Typescript/ES6 because I needed to extend it and found the original es3 style too hard to follow.  you can see that in my ```chain-proxy``` project on npm
=> add type definitions for use with Typescript.

README.md
onResponseEnd callback doesn't receive the parameter chunk so it doesn't make sense to reference it in the example.
=> Updating onResponseEnd example in README.md

lib/proxy.js
Fixes #131 (option 1)
Listen to the websocket server error event (which in turn listens to the http server error event) and not the http server error event directly.
=> Avoid uncaught exception on http server error

lib/proxy.js
The `ws` API changed such that `upgradeReq` is no longer a property of the web socket object. The request is instead passed as an additional parameter to the connect event handler.
Fixes #140
=> Fix compatibility with updated ws dependency

lib/proxy.js
Fix to https://github.com/joeferner/node-http-mitm-proxy/issues/146
=> Add binding IP for httpsServer as well. 

lib/proxy.js
an optimization in version 3.0 of the required proxy server [ https://github.com/websockets/ws/issues/1114 ]drops the upgradeReq parameter to save 20% in memory.  This breaks non-http(s) requests that use upgrade to switch - like web sockets (ws and wss).  This was never a consideration for he mitm proxy (I guess since the package specifies version 3.2 and up - so it never worked).  This matters for me so we re include it per the recommendation from the package maintainers [ https://github.com/websockets/ws/pull/1099 ]
=> fix upgradeReq is undefined

lib/proxy.js, test/01_proxy.js
WebSocket proxying was broken in https://github.com/joeferner/node-http-mitm-proxy/commit/b59c010f65ba1fe6542ac01aab9230e15bbdd074. This fixes them, and adds a unit test that was failing, but now passes.
=> Fix WebSocket Proxying

index.d.ts
Otherwise you can't write this:
```typescript
proxy.onRequest((ctx, __callback) => {
return __callback();
});
```
=> update for typescript v2.7

lib/proxy.js
This is an attempted solution for #73 and #74 related to authenticating HTTPS and websocket connections. 
You can indeed hook into the CONNECT process to return a 407 status and then get the client to send the proxy-authorization header as suggested in the comments of the above mentioned issues. 
The problem is that the headers sent during CONNECT are not associated with the request or websocket context in any way.
I'm not sure if my fix is ideal, but it seems to work well to ensure we can get the proxy credentials on each request and websocket connection.
=> Include CONNECT headers in the contexts

lib/proxy.js
Sorry for changing this so quickly after my previous pull request :). I needed to be able to get access to the IP address of the requestor so I changed this to add the entire connect request to the context instead of just the headers. Seemed like something others might find useful as well.
=> Include entire CONNECT request in the contexts not just headers

index.d.ts, lib/proxy.js, package.json
`debug` is the defacto standard for logging in Node.js.
This replaces the `silent` option. To see output, enable `http-mitm-proxy` with env variable:
```
$ DEBUG=http-mitm-proxy node myproxy.js
```
=> replace console.logs with debug

lib/proxy.js
```js
const proxy = require('http-mitm-proxy')()
proxy.listen({ port: 0 }, () => console.log('Proxy server is listening on port', proxy.httpPort))
```
=> Using port 0 to listen on arbitrary unused port

lib/proxy.js, package-lock.json, package.json
I came across an issue with the testing library Cypress when used together with this proxy library. Cypress didn't handle responses with empty body and transfer-encoding set to chunked very well. An issue is raised with Cypress to address that, but I made this workaround which I think makes sense.
If there are no response filters used, the response body will not change. Hence there is no need to change the transfer-encoding to chunked, just leave it like it is. I think this will generally work better for proxy clients that do not expect empty chunked responses.
Also updated some dependencies.
=> Only use chunked encoding when required

.gitignore, lib/proxy.js, test/01_proxy.js
After further consideration, my last PR was a bit too optimistic. 
This PR checks if onResponseData, ctx.onResponseData or ctx.addResponseFilter have been used to determine if chunked encoding needs to be applied. The response content might be modified through any of these methods.
Also added unit tests to verify the logic.
=> Safer handling of chunked transfer

examples/forwardHttps.js, lib/proxy.js, test/01_proxy.js
When using this proxy for https sites in keep-alive scenarios I found that my application would not exit, since there were still open connections even after calling proxy.close(). 
This PR makes sure that tunnels to "internal" https proxy servers are properly closed when the client disconnects. 
Also updated the example code for direct tunnels (forwardHttps) and some minor fixes to unit tests.
If this PR is accepted, please make a new npm release. I have another project which uses this library and would prefer to reference a released version rather than a github link in package.json. Thanks in advance.
=> Https socket close

lib/ca.js, test/01_proxy.js
Using 1024 bit server certificates causes App Transport Security failures on iOS when perfect forward security (PFS) is enabled. This doesn't manifest in all cases (e.g. browsing using Safari works fine with the proxy enabled and 1024 keys) but does show up when testing with `nscurl --ats-diagnostics`.
With 1024 bit, PFS enabled:
```
Default ATS Secure Connection
---
ATS Default Connection
ATS Dictionary:
{
}
2019-07-12 10:47:23.171 nscurl[55346:1341935] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
Result : FAIL
Error : Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, …
```
=> Switch server certificates to 2048 bits

lib/proxy.js, test/01_proxy.js
When initially establishing a CONNECT tunnel, if the socket has an error before makeConnection attaches the error handler it can result in an unhandler error event bubbling up and killing the node process. This pull attaches the socket error handler sooner to handle this.
=> Handle socket errors in CONNECT method negotiation

lib/proxy.js
In the absence of a HOST in the request headers , the MITM **crashes**.
  
The "_parseHostAndPort_" function returns NULL if the HOST does not exist in the headers.
When the result is NULL, the MITM generates an error and **EXIT**.
The MITM should either 1) display an error message and continue to run normally or 2) send a 400 response to the client.
The changes made in this pullrequest (on "__onHttpServerRequest_" function) helps to better manage the absence of a HOST in the headers of a request.
=> Update proxy.js - Absence of HOST in headers

lib/proxy.js
In the MITM, urls containing a **simple quote** are not encoded in the same way when it's http or https :
- **http** request : the MITM encodes the simple quote and replace it with %27.
- **https** request : the MITM does not encode the simple quote.
The problem is `url.parse(req.url)` used in the **parseHostAndPort** function when it is a http request. `parse()` replaces the simple quote with %27.
I have rewritten the function **parseHostAndPort** so that it no longer uses the `parse()` method to get host and port. I use the regular expression instead to get them.
=> Update proxy.js - Problem with url.parse(req.url)

lib/ca.js
This satisfies the new requirements in iOS 13 and Catalina for trusted certificates.
Fixes #208.
=> Reduce validity period to 2 years

lib/proxy.js
- the `async` library does not allow additional parameters in the callback  
- parameters have the value `undefined`  
- see https://caolan.github.io/async/v3/docs.html#each  
- this PR uses the parent scope values instead  
- fixes #220
=> Fix websocket close code propagation

README.md, lib/proxy.js
Quoting Node `server.listen` [documentation](https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback)
> If host is omitted, the server will accept connections on the unspecified IPv6 address (::) when IPv6 is available, or the unspecified IPv4 address (0.0.0.0) otherwise.
> In most operating systems, listening to the unspecified IPv6 address (::) may cause the net.Server to also listen on the unspecified IPv4 address (0.0.0.0).
The broad bind to all interfaces is an insecure default, so better the user/developer provide explicit confirmation of this configuration.
---
Follows https://github.com/joeferner/node-http-mitm-proxy/pull/147#issuecomment-346997595 suggestion
=> Default listen on 'localhost'

lib/proxy.js
connectRequests were not properly freed, errors were not handled correctly.
Since this is a duplex stream, the connection needs to be closed manually on error.
sslSemaphores were not being deleted at all.
Please notice that the deletion of semaphores can be done better, a comment on this would be great.
=> Fix big memory leak

lib/ca.ts
Certificates generated after 2020-09-01 with validity longer than 398 days will generate `ERR_CERT_VALIDITY_TOO_LONG` error in all major browsers ([Chrome](https://chromium.googlesource.com/chromium/src/+/HEAD/net/docs/certificate_lifetimes.md), [Firefox](https://blog.mozilla.org/security/2020/07/09/reducing-tls-certificate-lifespans-to-398-days/), [Safari](https://support.apple.com/en-us/HT211025)).
This PR reduces the validity period from 2 years to 1 year.  
Note that the CA is still valid for 2 years — and this should be fine.
=> Reduce generated server cert validity period to 1y

lib/proxy.ts
The callback parameters for `socket.on("message")` changed in [this commit](https://github.com/websockets/ws/commit/e173423c180dc1e4e6ee8938d9e4376a7a8b9757) and so `flags` is actually just indicating whether the frame is binary or ASCII text in case of type `message`
This is also mentioned in [the docs](https://github.com/websockets/ws/blob/master/doc/ws.md#event-message)
=> fix: websocket binary frame handling

package.json
Currently, it points to a non-existent file, which breaks TypeScript.
Should fix #274
=> Fix `types` field to point to the correct path

lib/proxy.ts
should fix [[options.port](https://github.com/joeferner/node-http-mitm-proxy/issues/248)](https://github.com/joeferner/node-http-mitm-proxy/issues/248).
Port property is currently Object not integer
=> fix proxy.ts - forceSNI

lib/proxy.ts
**Problem:**
Previously, the proxy server's handling of WebSocket connections overlooked the sec-websocket-protocol header, which is critical for specifying subprotocols. For example, when a client requested to establish a WebSocket connection with a specific protocol (e.g., json.reliable.webpubsub.azure.v1 for chatgpt), the proxy would initiate the connection without passing along the requested protocol. This oversight could lead to connection failures or incorrect server behaviors, as the server might not respond with the necessary connection message if the expected protocol was not specified. An example of this issue was observed on the "chatgpt" page, where omitting the protocol led to malfunctioning due to the server's expectation for a specific subprotocol to establish a WebSocket …
=> Enhanced WebSocket Protocol Handling in Proxy Server Connections
